# Generated by Django 3.2.1 on 2022-04-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_details', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['commented_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='avatars/')),
                ('profile_bio', models.TextField(blank=True, default='Hi, thanks for visiting my page. Follow me for awesome content!', max_length=500)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.TextField()),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('image_comment', models.ForeignKey(default='comments', on_delete=django.db.models.deletion.CASCADE, to='instaclone.comments')),
                ('image_likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('profile_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.profile')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaclone.profile'),
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='instaclone.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='instaclone.profile')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
